#!/usr/bin/env bash

set -e 

NAME="$(basename "$0")"
VERSION="0.1"


# Some defaults
COLOR="#34c0eb"
CONFIG="$HOME/.config/rofi/chief-list.csv"


parse_options(){
    # parse cli options
    if ! OPTS=$(getopt --options=h,c:,C: --long help,color:,config:,no-icons,combi: --name "$0" -- "$@");then
        echo -en "\0markup-rows\x1ftrue\n"
        echo "<span foreground='#f2422e'>Failed to parse options!</span>"
        exit 1
    fi
    eval set -- "$OPTS"

    while true;do
        case "$1" in 
            --help | -h )
                echo "$NAME $VERSION"
                echo
                echo "Rofi-Chief needs to be used in script mode."
                echo
                echo "Usage:"
                echo "  rofi -show mode -modi \"mode:$NAME [options]\""
                echo
                echo "Options:"
                echo "  -h, --help"
                echo "    Show this help text."
                echo "  -c <COLOR>, --color <COLOR>"
                echo "    Adds some styling to icons by coloring it with specified color."
                echo "    Defaults: ${COLOR}."
                echo "  -C <path/file.csv>, --config <path/file.csv"
                echo "    Determines items in rofi menu and what actions to perform."
                echo "    Needs to be a csv file with ';' as seperator. See README for more information on layout."
                echo "    Defaults: ${CONFIG}."
                echo "  --no-icons"
                echo "    Disables the use of icons in rofi menu."
                echo
                shift
                exit 0
                ;;
            --combi )
                args=$2
                shift 2
                if [[ $ROFI_RETV == 0 ]]; then
                    exit 1
                fi
                coproc ( rofi -combi-modi $args -modi combi -show combi )
                exit 0
                ;;
            --color | -c )
                COLOR="$2"
                shift 2
                ;;
            --config | -C )
                CONFIG="$2"
                shift 2
                ;;
            --no-icons )
                NO_ICONS=true
                shift
                ;;
            -- )
                shift
                break
                ;;
            * )
                echo "Unknown option $1" 1>&2
                exit 1
        esac
    done
}

declare -A actions
declare -A icons


parse_options "$@"

echo -en "\0markup-rows\x1ftrue\n"

while IFS=';' read -r key icon value; do
    value=$(sed -E "s;SCRIPTS;$HOME/.config/rofi/scripts;" <<< "$value")
    actions[$key]="$value"
    icons[$key]="$icon"
done < "$CONFIG"

if [ ! -z $ROFI_INFO ];then
    # Execute specified command
    CALLER=$ROFI_INFO
    unset ROFI_INFO
    coproc ( ${actions[$CALLER]}  > /dev/null  2>&1 )
else
    # Change prompt message
    echo -en "\0prompt\x1fChief\n"

    if [ $NO_ICONS ];then
        unset icons
    fi

    for key in "${!actions[@]}"; do
      echo -en "<span foreground='$COLOR'>${icons[$key]}</span> $key\0info\x1f$key\n"
    done
fi
